### PR TITLE
Bugfix/get error

### PR DESCRIPTION
**Pull request by sFreezer**

### CODE REVIEW

**Comment by samayo** [comment]
Hey, thanks for the PR, but I see no bug in here. `getError` should be able to return a boolean (false) if there are no errors

**Comment by sFreezer** [comment]
You're right, the name of the branch is not optimal, but the changes are correct.
The variable 'error' is initialized as an empty string and is never set to false.

**Comment by sFreezer** [comment]
you can make is to mixed (string and boolean) but in your implementieren it is initialized as an empty string  and never set to a boolean.
/**
     * @var string storage for any errors
     */
    private $error = '';

**Comment by sFreezer** [comment]
to mix types is always bad practices.

**Comment by sFreezer** [comment]
what do we do with the pr ?

**Comment by samayo** [comment]
I will merge it. Sorry been busy lately but I havent forgotten about the 2 PRs

**Pull request merged**
