### PR TITLE
getimagesize() failure

### PR DESCRIPTION
**Pull request by AsukaYuki**
If getimagesize() fails, couse a user uploaded a none image file, a php E_NOTICE is thrown.
I added validateImageSize() to be able to output a custom error message, instead of throwing a E_NOTICE
It is used in upload().
If it returns false, the error message "mimeTypes" in upload() will be set and upload() returns null.

### CODE REVIEW

**Comment by samayo** [comment]
Are you sure about the error? I just tested in local and trying to upload non-image files does not issue an `E_NOTICE` error.

**Comment by AsukaYuki** [comment]
Hi, i tested it in two different enviroments. I got errors in both
First in php nova framework.
Second with a very simple index.php looking like this:

```
<?php

require_once "/var/www/html/test/samayo/bulletproof/src/bulletproof.php";

$image = new Bulletproof\Image($_FILES);

$image->setLocation('/var/www/html/test/');
if($image["pictures"]){
    $upload = $image->upload();
    if($upload){
        echo $upload->getFullPath(); // uploads/cat.gif
    }else{
        echo $image["error"];
    }
}
?>

<form method="POST" enctype="multipart/form-data">
    <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>
    <input type="file" name="pictures"/>
    <input type="submit" value="upload"/>
</form>
```

This pops up in my Apache log file.
```
[Sun May 14 19:33:14.207038 2017] [:error] [pid 13929] [client 79.247.105.78:62272] PHP Notice:  getimagesize(): Read error! in /var/www/html/test/samayo/bulletproof/src/bulletproof.php on line 326, referer: http://178.238.227.53/html/test/
[Sun May 14 19:33:14.207272 2017] [:error] [pid 13929] [client 79.247.105.78:62272] PHP Notice:  getimagesize(): Read error! in /var/www/html/test/samayo/bulletproof/src/bulletproof.php on line 311, referer: http://178.238.227.53/html/test/
[Sun May 14 19:33:14.207374 2017] [:error] [pid 13929] [client 79.247.105.78:62272] PHP Notice:  exif_imagetype(): Read error! in /var/www/html/test/samayo/bulletproof/src/bulletproof.php on line 127, referer: http://178.238.227.53/html/test/

```

Maybe you dont see the E_NOTICE because your php log level excludes it.

**Comment by HMAZonderland** [comment]
Hackers might be able to spoof your incoming payload. The `getimagesize` also contains a warning about not validating the mime-type with this function. But to use the `get_mime_type` function.

See: http://php.net/manual/en/function.getimagesize.php

> Do not use getimagesize() to check that a given file is a valid image. Use a purpose-built solution such as the Fileinfo extension instead.

**Comment by samayo** [comment]
closing as fixed!

**Pull request closed without merging**
