### PR TITLE
Moved all messages in a configurable array and added setErrorMessages method

### PR DESCRIPTION
**Pull request by lordgiotto**
Because I needed to localize the error messages that your library returns, I created a private property $error_messages and a method setErrorMessages which accepts an array that will be recursively merged with $error_messages. Doing this way, anyone can localize your library for his needs: I think it could be very usefull... it was very usefull to me at least ;)

### CODE REVIEW

**Comment by lordgiotto** [comment]
Hi @samayo, any feedback? Don't you like it?

**Comment by samayo** [comment]
Sorry for the delay lordgitto. My laptop broke a some months ago and I halted all activity since then. One the surface and from my mobile this seems like a very good idea. If we can minimize the verbosity by a bit it will even be better. But I like it already. I'm getting new laptop on monday so I will hopefully take another look and merge it.

**Comment by lordgiotto** [comment]
Ok, thank you @samayo :) If you want me to change something, let me know!

**Comment by samayo** [comment]
Ok. I will. :)

**Comment by samayo** [comment]
Sorry for all the delay. I have integrated your PR. Thanks :+1:

**Pull request merged**
